#!/bin/bash
IDE_NAME=bsg

ide module dev

if [[ -z "$IDE_CMD" ]] ; then
    clear
    echo "Welcome to the $IDE_NAME shell!"
    PS1="\[\033[01;31m\]$IDE_NAME\[\033[00m\] $PS1"
    tree -dAL 2 "$IDE_HOME"
fi
